# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c2bc299a9b33dd16fcd457b89d12ee8"
name = "product-table-app"
handle = "product-table-app"
application_url = "https://collective-cop-mean-cable.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://collective-cop-mean-cable.trycloudflare.com/auth/callback",
  "https://collective-cop-mean-cable.trycloudflare.com/auth/shopify/callback",
  "https://collective-cop-mean-cable.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
